import { FormEvent, useEffect, useRef, useState } from "react";

type Child = { id: string; name: string; schoolYear: string };
type Question = { presentation: { accessibleText: string }; task: { operation: string; left: number; right: number; result: number; missing: string } };
type Session = { id: string; childId: string; question: Question; activityType: string; reason: string; targetQuestions: number };
type Dashboard = { attempts: number; accuracy: number; latency: number; recent: Array<{ correct: number; latencyMs: number; reason: string }> };
const apiBase = window.location.pathname.startsWith("/math-drill") ? "/math-drill/api/v1" : "/api/v1";
async function api<T>(path: string, init?: RequestInit, token?: string): Promise<T> { const response = await fetch(`${apiBase}${path}`, { headers: { "content-type": "application/json", ...(token ? { authorization: `Bearer ${token}` } : {}) }, ...init }); if (!response.ok) throw new Error((await response.json().catch(() => ({ message: "Something went wrong." }))).message); return response.json(); }
const symbol: Record<string, string> = { addition: "+", subtraction: "−", multiplication: "×", division: "÷" };
function equation(question: Question) { const t = question.task; return `${t.missing === "left" ? "?" : t.left} ${symbol[t.operation]} ${t.missing === "right" ? "?" : t.right} = ${t.missing === "result" ? "?" : t.result}`; }
function sound(ok: boolean) { try { const audio = new AudioContext(); const oscillator = audio.createOscillator(); const gain = audio.createGain(); oscillator.type = ok ? "sine" : "triangle"; oscillator.frequency.setValueAtTime(ok ? 760 : 175, audio.currentTime); if (ok) oscillator.frequency.exponentialRampToValueAtTime(1120, audio.currentTime + .11); gain.gain.setValueAtTime(.09, audio.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audio.currentTime + .22); oscillator.connect(gain).connect(audio.destination); oscillator.start(); oscillator.stop(audio.currentTime + .23); } catch { /* Sound is optional; visual feedback always remains. */ } }

export function App() {
  const [children, setChildren] = useState<Child[]>([]); const [view, setView] = useState<"landing" | "kid" | "pin" | "parent">("landing"); const [child, setChild] = useState<Child>(); const [session, setSession] = useState<Session>(); const [answer, setAnswer] = useState(""); const [started, setStarted] = useState(0); const [flash, setFlash] = useState<"correct" | "wrong" | "">(""); const [pin, setPin] = useState(""); const [configured, setConfigured] = useState(true); const [accessToken, setAccessToken] = useState(""); const [error, setError] = useState(""); const [dashboard, setDashboard] = useState<Dashboard>(); const [newName, setNewName] = useState(""); const answerInput = useRef<HTMLInputElement>(null);
  const loadChildren = () => api<Child[]>("/children").then(setChildren);
  useEffect(() => { void loadChildren(); }, []);
  useEffect(() => { if (view === "parent" && child && accessToken) void api<Dashboard>(`/children/${child.id}/dashboard`, undefined, accessToken).then(setDashboard); }, [view, child, accessToken]);
  async function chooseChild(profile: Child) { setChild(profile); setView("kid"); const next = await api<Session>("/sessions", { method: "POST", body: JSON.stringify({ childId: profile.id, mode: "DAILY" }) }); setSession(next); setStarted(Date.now()); setTimeout(() => answerInput.current?.focus(), 0); }
  async function submitAnswer(event?: FormEvent) { event?.preventDefault(); if (!session || !child || !answer.trim()) return; const result = await api<{ score: { correct: boolean }; question: Question; activityType: string; reason: string }>(`/sessions/${session.id}/attempts`, { method: "POST", body: JSON.stringify({ childId: child.id, question: session.question, response: answer, latencyMs: Date.now() - started, activityType: session.activityType, reason: session.reason }) }); const state = result.score.correct ? "correct" : "wrong"; sound(result.score.correct); setFlash(state); setAnswer(""); window.setTimeout(() => { setSession(current => current ? { ...current, question: result.question, activityType: result.activityType, reason: result.reason } : current); setFlash(""); setStarted(Date.now()); answerInput.current?.focus(); }, result.score.correct ? 420 : 760); }
  async function openParent() { const access = await api<{ configured: boolean }>("/parent/access"); setConfigured(access.configured); setPin(""); setError(""); setView("pin"); }
  async function unlock(event: FormEvent) { event.preventDefault(); try { const endpoint = configured ? "/parent/login" : "/parent/setup"; const result = await api<{ token: string }>(endpoint, { method: "POST", body: JSON.stringify({ pin }) }); setAccessToken(result.token); setView("parent"); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Could not unlock parent mode."); } }
  async function addProfile(event: FormEvent) { event.preventDefault(); if (!newName.trim()) return; const profile = await api<Child>("/children", { method: "POST", body: JSON.stringify({ name: newName, schoolYear: "P4" }) }, accessToken); setNewName(""); await loadChildren(); setChild(profile); }
  if (view === "kid" && child && session) { const enter = (key: string) => { if (key === "backspace") setAnswer(current => current.slice(0, -1)); else setAnswer(current => current.length < 9 ? `${current}${key}` : current); answerInput.current?.focus(); }; return <main className={`kid-screen ${flash}`}><button className="exit-kid" onClick={() => { setView("landing"); setSession(undefined); }}>×</button><div className="kid-question"><h1 aria-label={session.question.presentation.accessibleText}>{equation(session.question)}</h1><form onSubmit={submitAnswer}><label className="sr-only" htmlFor="answer">Your answer</label><input id="answer" ref={answerInput} inputMode="numeric" autoComplete="off" value={answer} onChange={event => setAnswer(event.target.value)} /><button className="keyboard-check" aria-label="Check answer">→</button></form><div className="number-pad" aria-label="Number keypad">{["1", "2", "3", "4", "5", "6", "7", "8", "9"].map(key => <button type="button" key={key} onClick={() => enter(key)}>{key}</button>)}<button type="button" className="pad-backspace" aria-label="Delete last digit" onClick={() => enter("backspace")}>⌫</button><button type="button" onClick={() => enter("0")}>0</button><button type="button" className="pad-submit" aria-label="Check answer" onClick={() => void submitAnswer()}>✓</button></div></div><div className="answer-flash" aria-live="polite">{flash === "correct" ? "✓" : flash === "wrong" ? "×" : ""}</div></main>; }
  if (view === "pin") return <main className="entry"><section className="pin-card"><button className="back" onClick={() => setView("landing")}>← Back</button><p className="eyebrow">Parent mode</p><h1>{configured ? "Enter your PIN" : "Set a parent PIN"}</h1><p>{configured ? "Parent tools and reports are protected on this device." : "Choose a 4–12 digit PIN. This is a simple household gate, not an Internet account."}</p><form onSubmit={unlock}><input aria-label="Parent PIN" autoFocus inputMode="numeric" type="password" pattern="[0-9]*" value={pin} onChange={event => setPin(event.target.value)} /><button>Continue</button></form>{error && <p className="error">{error}</p>}</section></main>;
  if (view === "parent") return <main className="parent"><header><button className="back" onClick={() => setView("landing")}>← Exit parent mode</button><div><p className="eyebrow">Parent view</p><h1>Math Drill</h1></div></header><div className="parent-layout"><section className="card"><h2>Children</h2><div className="profile-list">{children.map(profile => <button className={child?.id === profile.id ? "active" : ""} onClick={() => setChild(profile)} key={profile.id}>{profile.name}<small>{profile.schoolYear}</small></button>)}</div><form className="add-profile" onSubmit={addProfile}><label>Add a child profile<input value={newName} onChange={event => setNewName(event.target.value)} placeholder="Name" /></label><button>Add profile</button></form></section><section className="card report"><h2>{child ? `${child.name}'s practice` : "Select a child"}</h2>{child && <><div className="metrics"><span><b>{dashboard?.attempts ?? 0}</b> attempts</span><span><b>{dashboard?.accuracy ?? 0}%</b> accuracy</span><span><b>{dashboard?.latency ? `${(dashboard.latency / 1000).toFixed(1)}s` : "—"}</b> response</span></div><h3>Recent evidence</h3><ul>{dashboard?.recent.map((attempt, index) => <li key={index}>{attempt.correct ? "✓" : "×"} {Math.round(attempt.latencyMs / 100) / 10}s · {attempt.reason}</li>)}</ul></>}</section></div></main>;
  return <main className="entry"><section className="welcome"><p className="eyebrow">Math Drill</p><h1>Who is practising?</h1><div className="child-choices">{children.map(profile => <button key={profile.id} onClick={() => void chooseChild(profile)}>{profile.name}</button>)}</div><button className="parent-entry" onClick={() => void openParent()}>Parent mode</button></section></main>;
}
